 var resistance={
            x:0,
            y:0,
            width:80,
            height:20,
            outline:{
                lines:[
                    {
                        points:[0,15,20,15],
                        color:"#C37F7F",
                        width:2
                    },
                    {
                        points:[20,20,20,10],
                        color:"#7F7FFE",
                        width:2
                    },
                    {
                        points:[20,10,60,10],
                        color:"#7F7FFE",
                        width:2
                    },
                    {
                        points:[60,10,60,20],
                        color:"#7F7FFE",
                        width:2
                    },
                    {
                        points:[60,20,20,20],
                        color:"#7F7FFE",
                        width:2
                    },
                    {
                        points:[60,15,80,15],
                        color:"#C37F7F",
                        width:2
                    }
                ]

            },
            staticTexts:[
                {
                    x:0,
                    y:0,
                    text:"",
                    rotation:0
                }
            ],
            dynamicTexts:[
                {
                    x:0,
                    y:0,
                    text:"",
                    rotation:90
                }
            ]
        }